### ISSUE TITLE
"Foreign" type in `Interaction` in `scenegraph` module

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/typings#54]
![image](https://user-images.githubusercontent.com/25147704/60385399-0cf39d80-9a89-11e9-8733-123ff17d1741.png)

@ericdrobinson Any ideas? Since the type gets defined in the `interactions` module, it doesn't get recognized inside `scenegraph.d.ts`. Should this then be defined in the `index.d.ts` as global?

Thank you very much in advance.

**Comment by ericdrobinson** [comment]
Yes! The problem you have here is that the `Interaction` type is not included in the exported `class`. This is another instance wherein it is odd that you are exporting a class when you can never have instances of type `interactions`:

**Whenever you export a class, you make its constructor available to importers.**

Lots "classes" in the XD API do not allow instances. At the very least the constructor should be marked `private`. That said, these APIs are more likely intended to be accessors/modifiers and in such a light, treating them as members of a module or namespace is better aligned with the goal, I think. It's also frequently better aligned with reality. See the following:

```js
// OUTPUT: Object
console.log(require('interactions').constructor.name);
```
The `interactions` module doesn't even have its own class...

 In this case, I would suggest the following:

1. Convert the `interactions` `class` into a `module`.
1. Convert both `allInteractions` and `homeArtboard` properties into `const` declarations.
    - Behind the scenes these are actually implemented as getters with no setters, but that is more of an implementation detail. The result for the consumer of the API is identical.
1. Change the `homeArtboard` property declaration to:
   ```ts
   const homeArtboard: Artboard | null;
   ```
   as the `?` in Adobe's type annotations apparently means that value can be `null` rather than specifically `undefined`.
1. Move all of the `type` declarations into the `interactions` namespace.

The above done, you will be able to `import` the `Interaction` type into `scenegraph` via one of the following methods:

1. Top-level import:
   ```ts
   import { Interaction } from 'interactions';
   ```
1. Using `import`-types:
   ```ts
   readonly triggeredInteractions?: Array<import('interactions').Interaction>;
   ```

Either way should work fine now!

**Comment by pklaschka** [comment]
@ericdrobinson The problem I have with this is that this would – if I'm not mistaken – "suggest" that one can actually import this type (and possibly use it for `instanceof` type checking etc.). Since this is not possible for a plugin (as this isn't "more" than a type definition, making it "importable" would be wrong...

**Comment by pklaschka** [comment]
I've now solved this by moving those typedefs to the global namespace (in the `index.d.ts`). It passes the linters in VSCode and WebStorm – see 07a903ca7f28aebcbec62ce79248c4011a9125eb. @ericdrobinson Does that work for you? While it's probably not a very nice solution, it works without having "unreal" exports...

**Comment by ericdrobinson** [comment]
>The problem I have with this is that this would – if I'm not mistaken – "suggest" that one can actually import this type (and possibly use it for instanceof type checking etc.).

@pklaschka In this case, you are indeed mistaken. It took me a while to understand this as well, but there is a **_very_** important distinction between a `class` and just about everything else.

When you define a `class`, you are defining both the `type` **_AND_** a constructor function with the same name as that `type`. It's something like doing the following:

```ts
interface MyObject {
    new (): MyObject;
}

let MyObject: MyObject;
```

For a more complete example, check out the type declaration for [`Object` in lib.es5.d.ts](https://github.com/microsoft/TypeScript/blob/410b71751eb66d0ae99101870f307bb0f74a0b07/lib/lib.es5.d.ts#L267). Here's what's happening:

1. Declare `Object` and `ObjectConstructor` **types**. These interact with one-another.
1. Declare the ambient constant `Object` **name**.

By declaring the constant `Object` **name** you are now telling TypeScript that users can access that directly. If you only had the `interface`s (or `type`s), then you only have TypeScript _type names_ and attempting to add then to the right side of an `instanceof` will result in an error because there is no **name** associated with it.

So, when you declare a `class`, you are actually defining both the **type** and the **name**, which allows the "type" to appear on the right side of the `instanceof` in script without error.

>I've now solved this by moving those typedefs to the global namespace (in the `index.d.ts`). It passes the linters in VSCode and WebStorm – see 07a903c.

Please give the version I suggested a try. The global approach is strictly worse for two reasons:

1. The `type` declaration is globally accessible, which should make it 100% available to **_every_** context, not just ones wherein you `require('interactions')`.
1. The `type` declaration is no longer located in the module within which it is documented.

In my tests (in VSCode) with the `type` declarations defined in a module within `interactions.d.ts`, the following code results in an error:

```ts
// ERROR: Property 'Interaction' does not exist on type 'typeof interactions'.
let x = selection instanceof require('interactions').Interaction;
```

Which is expected as the `type` declaration did **_not_** define a type name. If WebStorm actually suggests that `Interactions` is a valid _name_ to use in this case, then this is a bug in WebStorm.

For the record, VSCode's IntelliSense doesn't even _suggest_ the `type`s in autocomplete:

![image](https://user-images.githubusercontent.com/9142587/60386207-3815c700-9a60-11e9-95ae-e0dc5b62f01c.png)

**Comment by pklaschka** [comment]
@ericdrobinson Understood. This, then, holds true for other modules as well, doesn't it? Specifically, I'll have to change `application`, `clipboard`, `commands`, and `viewport` as well, correct?

**Comment by pklaschka** [comment]
> @ericdrobinson Understood. This, then, holds true for other modules as well, doesn't it? Specifically, I'll have to change `application`, `clipboard`, `commands`, and `viewport` as well, correct?

As done in
d663c5a3d9e4b386251f7f95f28243c7d59b0dc0 2b3ea03c46968788d6e59b1cb22a04f788a28a85 63574ec279fc5fb441f72ab0c26a29886ea17e23 37b07a1ce7126156e81e6620b2e8b1bc5ba93ee9

**Comment by pklaschka** [comment]
Alright, in that case, this issue should be get resolved with the PR as well. If there are now more issues within the next two hours 😆, I'll merge the PR...

**Comment by ericdrobinson** [comment]
Was about to write something along the lines of "Yes" but you beat me to it!

If you attempt to do the following in XD you get an error:

```js
const viewport = require('viewport');
let v = new viewport();   // <-- Plugin TypeError: viewport is not a constructor
```

So these should be declared as `module`s. 😄

**Comment by pklaschka** [comment]
And, of course, @ericdrobinson: Thanks a lot (again) for your contributions. The great thing is that not only does this increase the quality of the typings, but I also feel like I have a better understanding of how TypeScript works now, so thanks on that "front" as well 👍

**Comment by ericdrobinson** [comment]
@pklaschka Happy to help! I'm very glad to hear that the conversation has helped you advance your understanding of TypeScript. That was a large portion of the motivation to provide suggestions with explanations instead of a monolithic PR with everything already packaged up.

And, honestly, this process clarified more TypeScript stuff for me as well! 😄

The one final question that I have is about the `let module: {exports:any};` global declaration in `index.d.ts`. That doesn't appear to be necessary [in VSCode]. Removing it changes nothing as `module` is already defined (in VSCode, at least?). Do things go poorly for you in WebStorm if this is removed?

**Comment by pklaschka** [comment]
@ericdrobinson Yep. Unfortunately, WebStorm lets you decide if you

1. activate NodeJS support for the project (which means you gain access to all the default Node modules and that it asks you if you want to run `npm install scenegraph` since it is an "unresolved" module)
2. deactivate this option for the project (which means WebStorm doesn't know those two anymore).

Therefore, as long as this (or these – counting `require()` as well) doesn't interfere with VSCode stuff, I'd like to leave it in to "explicitly" allow for CommonJS module im-/ exports.

**Comment by ericdrobinson** [comment]
Sounds good to me! I expected that it might be an environmental thing. Still not entirely sure where VSCode infers that definition from, but c'est la vie.

Otherwise, everything here looks great. This PR fixes a _massive_ amount of stuff and should really help clarify what's available to users! Great work!

**Comment by ericdrobinson** [comment]
Also, two more things:

1. Why does `index.d.ts` have the `export {};` line?
1. Why does `scenegraph.d.ts` use the more standard `export {...}` format instead of the `export =` approach that all other modules use?

**Comment by pklaschka** [comment]
> 1. Why does `index.d.ts` have the `export {};` line?

No idea, fixed in 8f7bd4fc077ea2bab3d92f9cc999f08ce2aa03b0



> 2\. Why does `scenegraph.d.ts` use the more standard `export {...}` format instead of the `export =` approach that all other modules use?

Equally, I have no idea. Whyever, it appears to work for scenegraph (imports work without any problems)... I have no idea what the decisive difference between `uxp` and `scenegraph` is, but it works 🤔

**Comment by ericdrobinson** [comment]
>I have no idea what the decisive difference between `uxp` and `scenegraph` is, but it works 🤔

I hate to rehash this now after `uxp` works, but does changing things in `uxp.d.ts` for you work as expected?

You mentioned [here](https://github.com/AdobeXD/typings/issues/49#issuecomment-505928580) that you used `export =` because it was the closest way to implement the CommonJS module export pattern.

_As I understand things_, using `export =` is a bit of a kludge and should go away as JavaScript evolves towards an ES2015+ module world. In my local environment, I tested modifying `uxp.d.ts` in the following manner:

1. Remove the wrapper `declare module uxp`.
1. Add `declare` to both the `shell` constant and the `storage` module.
1. Change `export = uxp;` to the following:
   ```js
   export {
       shell,
       storage
   }
   ```

I saw no errors in VSCode. Do you see errors in WebStorm if you try this pattern?

**Comment by pklaschka** [comment]
@ericdrobinson I have no idea why, but now, this works... Does that mean that all the other things (application etc.) should get exported another way as well?

**Comment by pklaschka** [comment]
At least I now think I've got an idea of why WebStorm couldn't resolve this before. Somehow, changing the branch messed up my project configuration (no idea why), resulting in some strange way of WebStorm interpreting only parts of it... Sorry about that.

**Comment by ericdrobinson** [comment]
>Does that mean that all the other things (application etc.) should get exported another way as well?

Basically, yes. But that said, it would be better, I think, to try a different approach. Please let me know if this works for you in `scenegraph.d.ts` and `uxp.d.ts` (two good test cases):

1. Remove the existing `export` statement.
1. Replace `declare` with `export`.

This is a quick test - the only items that should actually be exported are those that you want visible from outside of the module (read: internal types should not be exported). However, find-and-replace is a quick way to get a sense of whether this works or not...

**Comment by pklaschka** [comment]
@ericdrobinson Yep, that works.

**Comment by ericdrobinson** [comment]
Doing the above in VSCode changes the suggested property interpretation.

**Single `export {...}` Version:**
![image](https://user-images.githubusercontent.com/9142587/60387498-26d5b600-9a72-11e9-9f87-fee305a99dbf.png)

**Individual `export ...` Version:**
![image](https://user-images.githubusercontent.com/9142587/60387510-5dabcc00-9a72-11e9-9e0f-61e072d7b126.png)

Resolved names are different because of the global find-and-replace for a quick test.

**Comment by pklaschka** [comment]
Ok. That makes sense so far.

**Comment by ericdrobinson** [comment]
If you're okay with it, I would suggest changing the export process to be of this latter approach (`export class X`, `export interface Y`, `export const Z`, etc.). It provides you with supreme control as to whether or not the type will be available outside of the module without needing special workarounds.

**Comment by pklaschka** [comment]
@ericdrobinson Doing so right now 😉

**Comment by pklaschka** [comment]
PR should now be up-to-date with this way of exporting... 😅

**Comment by ericdrobinson** [comment]
Cool. I'll take a look. I've spotted something... unexpected with this route that I want to check on.

**Comment by pklaschka** [comment]
@ericdrobinson If everything's working for you, I'd go ahead and merge the PR. Writing the changelog for this release will take long enough as it is – I don't need any further things to put into one PR 😆

**Comment by ericdrobinson** [comment]
Agreed. That said, I'm seeing something unexpected (and struggling to understand it). Specifically, the following:

```js
const uxp = require('uxp');
uxp.   // <-- For autocomplete suggestions...
```

results in this in VSCode:

![image](https://user-images.githubusercontent.com/9142587/60387735-c8aad200-9a75-11e9-9116-0cc34652a135.png)

But... the `Shell` class isn't exported. 😕

**Comment by ericdrobinson** [comment]
@pklaschka Okay, I figured it out. The [plugin](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-plugin-d-ts.html) approach seems to work for the XD APIs by doing the following:

```ts
declare module 'scenegraph'
{
    interface Point {
    // ...
}

Basically, wrap the entire module in `declare module` and use a _**string**_ version of the module name: `'scenegraph'` instead of `scenegraph`.

Can you give that a shot and see if it works for you with WebStorm?

**Comment by ericdrobinson** [comment]
Also, please be careful to test with a strict `tsconfig.json` file around to catch errant `declare`s, etc.

**Comment by pklaschka** [comment]
@ericdrobinson Unfortunately, that doesn't work in WebStorm. It doesn't allow for checks like `node instanceof Text` which are, of course, vital for plugin development.

**Comment by pklaschka** [comment]
It works for the `uxp` module, though. Also, everything else works. It's only `instanceof` that breaks with this.

**Comment by ericdrobinson** [comment]
@pklaschka Let me look into it a bit. I say that because I _think_ this is the "correct" path. The structure I suggested appears to be how you're 'supposed' to declare [ambient modules](https://www.typescriptlang.org/docs/handbook/modules.html#working-with-other-javascript-libraries).

Let me quickly check the `instanceof` case with `scenegraph.d.ts`...

**Comment by pklaschka** [comment]
Correction: All hell breaks loose in WebStorm when I do that. It simply "accepts" everything as "correct" code and does no type checking or autocompletion whatsoever...

**Comment by pklaschka** [comment]
@ericdrobinson I was able to get everything to work as expected by having

```js
interface Shell {
  [...]
}
```

instead of

```js
declare class Shell {
  [...]
}
```

**Comment by ericdrobinson** [comment]
Did you try:

```ts
class Shell {
    [...]
}
```

?

The problem should have been the `declare` statement, not that it was an `interface` vs `class`...

**Comment by ericdrobinson** [comment]
I [mentioned above](https://github.com/AdobeXD/typings/issues/54#issuecomment-506977012) that you need to get rid of `declare` when you wrap the modules in `declare module 'name'` but you may have missed it...

I also suggested that you re-add the `tsconfig.json` file so that you can be notified about such errors. 😄

**Comment by pklaschka** [comment]
"A declare modifier is required for a top level declaration in a .d.ts file" for `class Shell` – I've added the tsconfig.json back in a few commits ago 😉

**Comment by pklaschka** [comment]
![image](https://user-images.githubusercontent.com/25147704/60388224-95386980-9aae-11e9-848e-181fa3a940b7.png)

**Comment by pklaschka** [comment]
Just to be clear: By 

> I was able to get everything to work as expected by having
> 
> ```js
> interface Shell {
>   [...]
> }
> ```
> 
> instead of
> 
> ```js
> declare class Shell {
>   [...]
> }
> ```
> 
> cf. [b0a1352](https://github.com/AdobeXD/typings/commit/b0a1352c1140ef37db8c02fd0ca3d39affa01fa0)

I meant without the "ambient module" declarations...

**Comment by ericdrobinson** [comment]
>I meant without the "ambient module" declarations...

How about _with_ the "ambient module" approach?

**Comment by ericdrobinson** [comment]
![image](https://user-images.githubusercontent.com/9142587/60388299-4c1bf180-9a7d-11e9-9325-843196845891.png)

**Comment by pklaschka** [comment]
> How about _with_ the "ambient module" approach?



> Correction: All hell breaks loose in WebStorm when I do that. It simply "accepts" everything as "correct" code and does no type checking or autocompletion whatsoever...

**Comment by ericdrobinson** [comment]
Does that include removal of the `declare` keyword when you made the move?

Also, did you try restarting WebStorm? (I've had to do that with VSCode in the past to get the language server to fully refresh...)

**Comment by pklaschka** [comment]
> Does that include removal of the `declare` keyword when you made the move?
> 
> Also, did you try restarting WebStorm? (I've had to do that with VSCode in the past to get the language server to fully refresh...)

Unfortunately, yes. The problem remains.

**Comment by pklaschka** [comment]
With the shell being an interface (and no ambient modules), however, everything appears to be working as expected in WebStorm and VSCode.

**Comment by ericdrobinson** [comment]
Yes, but the type information is incorrect. `Shell` actually _is_ a class, if memory serves.j

**Comment by ericdrobinson** [comment]
Let's provide an extremely simple test case. Please do the following:

1. Create a new file called `uxp2.d.ts`.
1. Add this script to it:
   ```ts
   class Shell {}
   
   declare module 'uxp2' {
       export const shell: Shell;
       export namespace storage {
           const fileSystem: any;
       }
   }
   ```
1. In your `sample.js` file, try the following:
   ```js
   const uxp2 = require('uxp2').storage.fileSystem;
   ```

Do you get any errors with any of that?

**Comment by pklaschka** [comment]
According to the documentation, Shell should be a global class. However, new Shell() also doesn't work in XD, meaning it could actually be an interface...

**Comment by pklaschka** [comment]
@ericdrobinson 
> Do you get any errors with any of that?

It isn't that I get any errors with ambient modules. It is the fact that I'm not getting ones, e.g., with

```js
const notMyShell = require('uxp');
notMyShell.openExternal('...');
```

Doesn't show an error. Basically, WebStorm just "gives up" on understanding the typings with the ambient modules and still provides some autocompletion, but doesn't actually "understand" the type flow (an object is of a certain type `b` in an `if (a instanceof b)` block, `uxp` does not equal `uxp.shell`) etc.

**Comment by pklaschka** [comment]
> Let's provide an extremely simple test case. Please do the following:
> 
> 1. Create a new file called `uxp2.d.ts`.
> 2. Add this script to it:
>    ```ts
>    class Shell {}
>    
>    declare module 'uxp2' {
>        export const shell: Shell;
>        export namespace storage {
>            const fileSystem: any;
>        }
>    }
>    ```
> 3. In your `sample.js` file, try the following:
>    ```js
>    const uxp2 = require('uxp2').storage.fileSystem;
>    ```
> 
> Do you get any errors with any of that?

![image](https://user-images.githubusercontent.com/25147704/60388475-805dd500-9ab2-11e9-950e-e8f619dc6ef8.png)

**Comment by ericdrobinson** [comment]
Yeah, that actually _should_ be `declare class Shell`. Restarting my VSCode instance revealed that same error (which is good!) 😄.

**Comment by pklaschka** [comment]
With the ambient module, the wrong code shows no error:
![image](https://user-images.githubusercontent.com/25147704/60388507-ec403d80-9ab2-11e9-85da-2d4ed90dc607.png)

but without this module declaration, everything works as expected:
![image](https://user-images.githubusercontent.com/25147704/60388514-07ab4880-9ab3-11e9-9c9c-2f560cf3b35b.png)

**Comment by ericdrobinson** [comment]
Okay, so it looks like declaring a class within a module will _also_ cause it to _export_ the name. If we want a _type_ to exist in/for a module, then we need to use `interface` instead of `class`. There are ways to get an `interface` to work like a `class`, of course, but if the `class` isn't "public" in the module anyway, then it is probably _not_ meant to be `new`ed up.

Seems as though your approach of converting any `class` that shouldn't be exported into an `interface` is indeed the correct approach.

I tested the `uxp.shell` instance's constructor and, while it exists, it's name is "b" and almost _certainly_ isn't meant to be used... 😜

**Comment by pklaschka** [comment]
> I tested the `uxp.shell` instance's constructor and, while it exists, it's name is "b" and almost _certainly_ isn't meant to be used... 😜

I actually just tested this myself and wanted to write the exact same thing.

So, I'll leave it the state it is in (b0a1352c1140ef37db8c02fd0ca3d39affa01fa0) and merge it? 

If you'd like / you agree, I'd like to add you to the contributor's list in the `package.json` (since credit is definitely due to you here). For that, I would need name, url and email address of your choice:

```json

    {
      "name": "",
      "email": "",
      "url": ""
    }
```

**Comment by ericdrobinson** [comment]
A few last minute items!

### Repo Structure - New Issue?
I would like to suggest that the `jsconfig.json` and `sample.js` file get moved into a `sample` or `example` folder that's separate from the top level. A `tsconfig.json` file at the top level then makes the most sense. This will allow a clear separation of TypeScript and JavaScript files while allowing you to have a `tsconfig.json` file that's designed specifically for _writing_ the declaration files.

Thoughts?

### Inaccessible Types Complication
I did a quick test of the `scenegraph` module and got the following:

```js
// Output:
// 
 GraphicNode,Rectangle,Ellipse,Line,Text,Path,Group,Artboard,BooleanGroup,RepeatGrid,SymbolInstance,LinkedGraphic,Matrix,Color,LinearGradient,RadialGradient,ImageFill,Blur,Shadow,root,selection,Polygon
console.log(Object.getOwnPropertyNames(require('scenegraph')));
```

When you compare those to the list of types currently available from `scenegraph.d.ts` you will notice that `RootNode` and `SceneNode` are not available.

This is a bit more complicated because classes "extend" from `SceneNode` (at least). This would need to change to `implements` for the sub-classes and then they would need to add all the properties.

Boo. I'm still playing around with this...

### Contributor Info
Thanks! I appreciate it.

- **Name:** Eric Robinson
- **Email:** eric - at - sonicbloom - dot - io
- **URL:** https://github.com/ericdrobinson

**Comment by pklaschka** [comment]
@ericdrobinson 



> ### Repo Structure - New Issue?
> I would like to suggest that the `jsconfig.json` and `sample.js` file get moved into a `sample` or `example` folder that's separate from the top level. A `tsconfig.json` file at the top level then makes the most sense. This will allow a clear separation of TypeScript and JavaScript files while allowing you to have a `tsconfig.json` file that's designed specifically for _writing_ the declaration files.

The thing is that this would mean that the `sample.js` file wouldn't work when cloning the repo, anymore, since the `jsconfig.json` is meant to be placed at the project root folder with a `types` folder as a sibling (the way it is now). This makes using the typings for JS basically a copy-and-paste solution in VSCode as one simply has to copy `types` and `jsconfig.json` into the project directory to use it.

Therefore, while I understand the request, it's a bit more complicated than that and I'd, therefore, suggest having this in a new issue discussing solutions and "apart" from the current Pull Request.



> ### Inaccessible Types Complication
> I did a quick test of the `scenegraph` module and got the following:
> 
> ```js
> // Output:
> // 
>  GraphicNode,Rectangle,Ellipse,Line,Text,Path,Group,Artboard,BooleanGroup,RepeatGrid,SymbolInstance,LinkedGraphic,Matrix,Color,LinearGradient,RadialGradient,ImageFill,Blur,Shadow,root,selection,Polygon
> console.log(Object.getOwnPropertyNames(require('scenegraph')));
> ```
> 
> When you compare those to the list of types currently available from `scenegraph.d.ts` you will notice that `RootNode` and `SceneNode` are not available.
> 
> This is a bit more complicated because classes "extend" from `SceneNode` (at least). This would need to change to `implements` for the sub-classes and then they would need to add all the properties.
> 
> Boo. I'm still playing around with this...

Interesting – one of my projects actually relies on such a type check. I guess it's time to hotfix that. However, I'd like to defer this into another pull request (as soon as we find a better-suiting solution) to not explode the current PR even further than it already is. Since the PR is mostly structure-related and this is an actual "content" mistake, that sounds like something that's going to be easy to merge with the next bigger update.



> ### Contributor Info
> Thanks! I appreciate it.
> 
> * **Name:** Eric Robinson
> * **Email:** eric - at - sonicbloom - dot - io
> * **URL:** https://github.com/ericdrobinson

Perfect, thank you. You're now added to the contributor list.

I'll now merge the Pull Request and open new issues for the two ideas to keep this (slightly) organized. After all, this is the 56th comment on this issue and we're already far off-topic from the original issue title 😉

**Comment by pklaschka** [comment]
> > ### Repo Structure - New Issue?
> > I would like to suggest that the `jsconfig.json` and `sample.js` file get moved into a `sample` or `example` folder that's separate from the top level. A `tsconfig.json` file at the top level then makes the most sense. This will allow a clear separation of TypeScript and JavaScript files while allowing you to have a `tsconfig.json` file that's designed specifically for _writing_ the declaration files.
> 
> The thing is that this would mean that the `sample.js` file wouldn't work when cloning the repo, anymore, since the `jsconfig.json` is meant to be placed at the project root folder with a `types` folder as a sibling (the way it is now). This makes using the typings for JS basically a copy-and-paste solution in VSCode as one simply has to copy `types` and `jsconfig.json` into the project directory to use it.
> 
> Therefore, while I understand the request, it's a bit more complicated than that and I'd, therefore, suggest having this in a new issue discussing solutions and "apart" from the current Pull Request.

moved to #57 



> > ### Inaccessible Types Complication
> > I did a quick test of the `scenegraph` module and got the following:
> > ```js
> > // Output:
> > // 
> >  GraphicNode,Rectangle,Ellipse,Line,Text,Path,Group,Artboard,BooleanGroup,RepeatGrid,SymbolInstance,LinkedGraphic,Matrix,Color,LinearGradient,RadialGradient,ImageFill,Blur,Shadow,root,selection,Polygon
> > console.log(Object.getOwnPropertyNames(require('scenegraph')));
> > ```
> > 
> > 
> > When you compare those to the list of types currently available from `scenegraph.d.ts` you will notice that `RootNode` and `SceneNode` are not available.
> > This is a bit more complicated because classes "extend" from `SceneNode` (at least). This would need to change to `implements` for the sub-classes and then they would need to add all the properties.
> > Boo. I'm still playing around with this...
> 
> Interesting – one of my projects actually relies on such a type check. I guess it's time to hotfix that. However, I'd like to defer this into another pull request (as soon as we find a better-suiting solution) to not explode the current PR even further than it already is. Since the PR is mostly structure-related and this is an actual "content" mistake, that sounds like something that's going to be easy to merge with the next bigger update.

moved to #56
