### ISSUE TITLE
'SceneNode' refers to a value, but is being used as a type here ts(2749)

### ISSUE THREAD

**Issue by velara3** [AdobeXD/typings#67]
I'm getting this message after importing the new type defs directory (today Sept 28). 

> 'SceneNode' refers to a value, but is being used as a type here.ts(2749)

And this error: 

>Property 'SceneNode' does not exist on type 'typeof import("/Users/user/Library/Application Support/Adobe/Adobe XD/develop/myplugin/types/scenegraph")'.ts(2339)

It happens on the `const` line and the `@param` line:  

```
// there's a red underline under scene node
const {SceneNode} = require("scenegraph");

/**
 * Adds interaction
 * @param {SceneNode} item
 **/
function addInteractions(item, model) {

}
```

**Comment by krisnye** [comment]
Have you tried

`import { SceneNode } from "scenegraph";`

**Comment by pklaschka** [comment]
Hi @velara3.

May I ask in which "context" you're experiencing this issue? What I mean is: Do you use it with JS in VSCode, in another IDE or editor, with a TS compiler?

Thank you very much in advance :slightly_smiling_face:

**Comment by velara3** [comment]
It's working now. It was an issue on my side.

**Comment by velara3** [comment]
Still have an issue. I see this in the release notes for #59 :
![image](https://user-images.githubusercontent.com/1084127/65843007-44c6e700-e2fd-11e9-9980-d974b0eeefbf.png)

**Comment by velara3** [comment]
Interesting. Is it possible for me to revert this locally? I have a lot of: 

     /** @param {SceneNode} */ 

Can I comment out a line and get old behavior back? Or can I import it? 

const {SceneNode} = require("scenegraph").SceneNode // doesn't work

**Comment by ericdrobinson** [comment]
@velara3 You can do one of the following:

### Cleanest Approach

```js
const scenegraph = require("scenegraph");

//...

/** @param {scenegraph.SceneNode} */
```

### Clean Approach

```js
/** @param {import("scenegraph").SceneNode} */
```

Find-and-replace would be your friend for that second ("Clean Approach") option. The first option, however, only requires that you refer to the imported `scenegraph` module before the `SceneNode`.

### Global Approach 

If you're really that keen on maintaining a generic `SceneNode` there, you  can also create your own `.d.ts` file in the types directory (something like "`custom.d.ts`") with the following line in it:

```ts
declare type SceneNode = import('scenegraph').SceneNode;
```

That will make it so that the definition of the `SceneNode` type is global for your project - no need to do any `require` or `import`.

**Comment by velara3** [comment]
I've created a custom .d.ts and it's working now. 

But I'm still having issues with other elements:

```
// Argument of type 'SceneNodeList' is not assignable to parameter of type 'Selection'.ts(2345)
async function updateMethod() {
	const { selection, root } = require("scenegraph");
	showDialog(selection, root); // error here
}


/**
 * Show dialog
 * @param {Selection} selection Selection
 **/
async function showDialog(selection, rootNode, showingPanel = false, showLabels = true) {
   ...

}
```

**Comment by pklaschka** [comment]
Yes, sorry, that is a typo on my end (making the `scenegraph.selection` a `SceneNodeList`). Unfortunately, when trying to use `Selection`, which is declared as a global interface, it is a basically a guessing game whether it uses the correct `Selection` interface or a class from the `dom` typings...

As discussed in #65, it is (currently) not feasible to provide own declarations for the DOM, meaning I currently see no elegant way around that. @ericdrobinson Any thoughts? The only thing I can think of right now (which I've done in 261fb02bae14220e862da0ca35ec430dc808a15d in the branch where I've just fixed this mistake) is to add some sort of "wrapper" for `Selection` with a unique name (in this case, `XDSelection`)...

**Comment by velara3** [comment]
"But professor, where would we ever need namespaces?" 

So the DOM typings and the XD typings with the same names are conflicting. 

Does ES6 or ES7 provide namespaces?

**Comment by velara3** [comment]
>>Does ES6 or ES7 provide namespaces?

>How would this help? What type of solution do you have in mind?

I like your suggestions but what I meant was maybe writing the classes in ES6? XD plugins are written in JavaScript. 

https://adobexdplatform.com/plugin-docs/reference/javascript/javascript-support.html

You could simply create an ES6 class and code hinting and code complete will work from that but if there are name collisions then namespaces would help if they are supported. 

The local ES6 classes might override the global types but I'll have to check.

**Comment by ericdrobinson** [comment]
>You could simply create an ES6 class and code hinting and code complete will work

This isn't possible for type _declarations_. As a plugin **_author_** you can definitely write using ES6 classes and the like. The Type Declarations, however, **_cannot_** be written in ES6, they **must** be written using TypeScript (and, more specifically, as Type Declaration files).

The Type Declaration files are _descriptions_ of the environment. The `Selection` type is provided by Adobe. It's a `type` only (and not a `class`) because you cannot do "`let sel = new Selection()`". TypeScript declaration files are _ambient_ - they do not affect output, but help the VSCode JavaScript language service understand what options are available for a value of a given type.

If you're familiar with C/C++, the Type Declaration files are _similar_ to Header Files for those languages. A simple way to think of Type Declaration files is that they define the **_shape_** of available APIs without actually declaring the APIs themselves.

In this case, as with browsers, the environment has a built-in `Selection` _type_. It is not something that you can create, but you can obtain values of that _type_. Unfortunately, the DOM lib defines the `Selection` type in the global namespace. Currently, the XD typings do the same exact thing, which causes the conflict.

>The local ES6 classes might override the global types but I'll have to check.

TypeScript declaration files allow you to declare class types. This will add both a _Type Name_ and _Value Name_ to IntelliSense. Example:

```ts
class Selection { /** ... **/ }
```

This adds both a Type called `Selection` and a Value called `Selection` (the thing you can use directly in the code to call, say, `new Selection()`.

```ts
interface Selection { /** ... **/ }
```

This adds **_only_** a Type called `Selection`. If you try to type `new S`, the `Selection` name won't show up. This is what we expect with XD as writing `new Selection()` in XD results in an error.

Make sense?
