### ISSUE TITLE
using with`@types/node` inflicts compiler error about duplicate definition

### ISSUE THREAD

**Issue by peterblazejewicz** [AdobeXD/typings#75]
Folks, thanks for great tooling!
Q: What was the reason behind adding the global declaration for `require`?
https://github.com/AdobeXD/typings/commit/bda80c1b27653d6977d58ded7f25d413534dc5be#diff-88bec6beae84369c0376b56b3bb88fe1R13
Should it work with `@types/node` in typical scenarios? The XD is based on the CommonJS(2), expects use of `module.exports = ....` and using `require(...)`. The @types/node ships with the `require` definition also in the global namespace:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L139

This setup results in the tsc complaining:
```bash
error TS2300: Duplicate identifier 'require'.
```
Thanks!

**Comment by pklaschka** [comment]
Hi @peterblazejewicz,

Since XD doesn't provide Node's modules, using `@types/node` isn't an ideal option. I had found editor support to be optimal when I added this declaration since, for editors that do support CommonJS, this didn't change anything. In other cases, it removed warnings about calling an *undefined function `require()`*...

All in all, it is, therefore (unfortunately) not really an option to use `@types/node` (and not recommended) since the only real overlap between XD's APIs and NodeJS is the CommonJS part.

Why do you "want" to have `@types/node` in your project, if I may ask :slightly_smiling_face:?

**Comment by peterblazejewicz** [comment]
Hey, thanks for getting back!
Let's say I'm using TS files solely, so as the CommonJS requires and has this export definition:
```
module.exports = {
  ....
}
```
The current types works OK when using with vanilla JS, with `allowJs` option or using `tsc` to check for errors, using `@ts-check` pragmas in source files, so in case like in this project sample:
https://github.com/AdobeXD/typings/blob/master/sample.js
But when used in `.ts` CommonJS files I think it needs definitions for Node (@types/node)

**Comment by peterblazejewicz** [comment]
Solved, I've rewritten the parts using CommonJS syntax to:
```ts
export const commands = {
  commandName: commandFunctionReference,
  ....
};
```
and this removes the need to use @types/node directly.
Thanks!
