### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by petrbrzek** [AdobeXD/typings#79]
Hello 👋 , 

I just wanted to ask whatever this project is still being actively developed. There is already Adobe XD v34 but the latest release of typings here is for v25. Thanks.

**Comment by pklaschka** [comment]
Hi there 🙂 

It is still alive, but it's maintained primarily by a student with a very limited amount of time (me 😜).

You can see the XD v29 PR (#77). Unfortunately, work, exams at university, and illness prevented me from getting to work on the repo since then.

All in all: Yes, it's still alive and maintained, I hope to get back to updating it soon. I'll review and merge any PRs, read every issue, etc., but updates may be slow.

**Comment by petrbrzek** [comment]
Thanks, I find funny that Adobe has 22 thousand employees, and they dedicate a student to maintain this repo. I'm not saying it's bad, but it's kind of obvious that it's hard for you to stay up to date with XD releases.

**Comment by pklaschka** [comment]
@petrbrzek The project started during the plugin APIs' prerelease stage when I needed these definitions myself and developed them. They then became part of this GitHub organization at a later stage (after being published in an old-school fashion through zip-files in the prerelease forums). They remained a personal side-project (hosted in this GitHub organization to become the "official" Typescript definitions).

All in all, it is, therefore, less dedicating me to it.  This repository is (in its origin and up to today) a community-driven (with me as a somewhat sole contributor and @ericdrobinson reviewing my PRs) project. It's supposed to be a solution until Adobe provides some more official solution (which, rumor has it, might hopefully happen more sooner than later with UXP now also being available in Photoshop 😉 ).

Just as a disclaimer (as someone might, otherwise, possibly misinterpret my previous comment): I am (at least for now, I silently hope that this might change in the future? 😅 ) not an employee at Adobe (just another plugin developer 😜 ). I also haven't officially been declared as this repository's maintainer. The project just started as a personal project, and at least for now, no one at Adobe has "taken over" the repo. 😉
